# Generated by Django 3.2.4 on 2021-09-04 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_edu', '0002_auto_20210904_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing_commented',
            new_name='note_commented',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_comment',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 45, 18, 730965)),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 45, 18, 725152)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 45, 18, 730965)),
        ),
    ]
